# Generated by Django 3.1.1 on 2020-09-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_products_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
    ]
